# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-09 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotav',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spotav',
            name='audio',
            field=models.FileField(blank=True, upload_to='spot-av'),
        ),
        migrations.AlterField(
            model_name='spotav',
            name='image',
            field=models.ImageField(blank=True, upload_to='spot-av'),
        ),
        migrations.AlterField(
            model_name='spotav',
            name='video',
            field=models.FileField(blank=True, upload_to='spot-av'),
        ),
    ]
