# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-15 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20180909_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotav',
            name='job_added_to_queue_once',
            field=models.BooleanField(default=False),
        ),
    ]
