# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-09 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotpage',
            name='date',
        ),
        migrations.AddField(
            model_name='spotpage',
            name='date_published',
            field=models.DateField(blank=True, null=True, verbose_name='Date article published'),
        ),
    ]
