# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-17 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0002_auto_20171209_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotpage',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
