# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-17 15:15
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0003_spotpage_facebook_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotpage',
            name='body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
    ]
