# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-17 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0004_auto_20180217_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotpage',
            name='date_published',
        ),
        migrations.AddField(
            model_name='spotpage',
            name='facebook_created',
            field=models.DateField(blank=True, null=True, verbose_name='Date article created'),
        ),
        migrations.AddField(
            model_name='spotpage',
            name='facebook_updated',
            field=models.DateField(blank=True, null=True, verbose_name='Date article updated'),
        ),
    ]
