# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-17 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0005_auto_20180217_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotpage',
            name='facebook_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date article created'),
        ),
        migrations.AlterField(
            model_name='spotpage',
            name='facebook_updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date article updated'),
        ),
    ]
