# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-11 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20180909_1259'),
        ('spots', '0006_auto_20180217_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotpage',
            name='spot_av',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='social.SpotAV'),
        ),
    ]
